version: '3.8'
services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=warehouse
      - POSTGRES_PASSWORD=warehouse
      - POSTGRES_DB=warehouse
    container_name: warehouse
    volumes:
      - ./data:/var/lib/postgresql/warehouse/data
    ports:
      - 5432:5432
